### ISSUE TITLE
Create Recursive Function - 0%

### ISSUE THREAD

**Issue by tomLendy** [tomLendy/r3velat1on#13]
#### Task(s)
- [ ] Review recursive functions. 
- [ ] Create a recursive function
- [ ] Merge into /src/functions.js
