### ISSUE TITLE
Async Await Examples - 0%

### ISSUE THREAD

**Issue by r3velations** [tomLendy/r3velat1on#14]
#### Task(s) 
- [ ] Research Async Await
- [ ] Create 2-3 functions using Async Await
- [ ] Test to ensure functions work as expected
- [ ] Merge into /src/functions.js
