### ISSUE TITLE
Review Heads Up JS section on DOM - 0%

### ISSUE THREAD

**Issue by tomLendy** [tomLendy/r3velat1on#15]
#### Task(s) 
- [ ] Log into O'Reilly account
- [ ] Find my copy of Heads Up JS
- [ ] Review section on DOM 
- [ ] Practice examples from the book.
